<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>酒业英雄联盟</title>
  <link rel="stylesheet" href="./build/style.css">
  <link href="./favicon.ico" type="image/x-icon" rel="shortcut icon">
</head>
<body>
  <img style='display: block;width: 65%;margin: 100px auto 20px;' src="/build/qr.png" alt="" />
  <p style='text-align: center;padding: 0 20px;'>请关注微信公众号后查看详细信息!</p>
</body>
</html>
