<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
  <meta name="renderer" content="webkit">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>优惠券使用规则</title>
  <style>
  	html, body {
      background-color: #fff;
    }
    body {
      margin: 0;
      -webkit-overflow-scrolling: touch;
      -webkit-box-sizing: border-box;
      -moz-box-sizing: border-box;
      box-sizing: border-box;
      word-wrap: break-word;
      color: #333;
      padding: 15px 3%;
      font: 14px/1.3 '\5FAE\8F6F\96C5\9ED1', STXihei, '\534E\6587\7EC6\9ED1', Roboto, Noto, arial, sans-serif;
    }
    a {
      color: inherit;
      text-decoration: none;
    }
    ul,li {
      padding: 0;
      margin: 0;
      list-style: none;
    }
    li {
      border-bottom: 1px solid #e6e6e6;
      margin-bottom: 10px;
      padding-bottom: 10px;
    }
    p {
      position: relative;
      padding-left: 15px;
      margin-bottom: 5px;
      margin-top: 0;
    }
    li p:first-child:before {
      position: absolute;
      content: 'Q';
      left: 0;
      top: 0;
    }
    li p:last-child {
      color: #666;
    }
    li p:last-child:before {
      position: absolute;
      content: 'A';
      left: 0;
      top: 0;
    }
  </style>
  <include file="public/wx_share" />
</head>
<body>
	<ul>
   <li>
     <p>优惠券可以干什么？</p>
     <p>支付时抵扣商品金额。实际以优惠券使用规则为准。</p>
   </li> 
   <li>
     <p>怎么获得优惠券？</p>
     <p>在邸达不定期推出的活动中获得。</p>
   </li> 
   <li>
     <p>一张优惠券能拆开多次使用吗？</p>
     <p>不能，一张优惠券只能一次性使用，不能分开使用。</p>
   </li> 
   <li>
     <p>下单的时候使用了优惠券，但是后来订单取消了，优惠券会返还吗？</p>
     <p>会，订单取消后优惠券会立刻返还到您的账户中。</p>
   </li> 
   <li>
     <p>如何使用优惠券？</p>
     <p>在订单结算时，点击“优惠券”，选择可用优惠券使用</p>
   </li> 
  </ul>
  <!--底部导航-->
</body>
</html>