<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
  <meta name="renderer" content="webkit">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>假货先赔</title>
  <style>
  	html, body {
      background-color: #fff;
    }
    body {
      margin: 0;
			padding: 20px;
      -webkit-overflow-scrolling: touch;
      -webkit-box-sizing: border-box;
      -moz-box-sizing: border-box;
      box-sizing: border-box;
      word-wrap: break-word;
      color: #333;
      font: 12px/1.3 '\5FAE\8F6F\96C5\9ED1', STXihei, '\534E\6587\7EC6\9ED1', Roboto, Noto, arial, sans-serif;
    }

    .fake-modal p {
    	margin-top: 0;
			margin-bottom: 5px;
			text-indent: 2em;
    }
		.fake-modal a {
		  color: #52b75a;
	    text-decoration: none;
	    -webkit-tap-highlight-color: transparent;
		}
  </style>
</head>
<body class='fake-modal'>
<p>亲，您已对订单 ({$Think.get.id}) 申请假货先赔，当您点击“假货先赔”按钮时，即已明确：</p>
<p>(1). 订单 ({$Think.get.id}) 立刻开启假货先赔处理，市场督查人员和品牌厂家会立即组织对问题货品的封存和假货鉴定，您需要全力配合做好货物封存和鉴定工作；</p>
<p>(2). 若订单 ({$Think.get.id}) 确属假货，邸达会直接在卖家账户扣除相应订单款项，并直接打款给您 (由于银行不同，货款会在1个工作日内退回到您的帐户) ，并且邸达会协助您做好理赔工作；您的信用评级由此可以获得提升，也有机会收获更多的优惠政策信息；</p>
<p>(3). 若订单 ({$Think.get.id}) 鉴定并非假货，需要您承担卖家的物流配送费用，具体金额由双方约定；</p>
<p><span>(4). 您有任何疑问，请随时致电邸达，</span><a href="tel: 4000798798">4000-798-798.</a></p>
<p>如您已明确以上信息，请点击“确认”提交假货先赔申请。</p>
</body>
</html>
