<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="renderer" content="webkit">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>首单减免</title>
  <style type="text/css">
    body {
      margin: 0;
      -webkit-overflow-scrolling: touch;
      -webkit-box-sizing: border-box;
      -moz-box-sizing: border-box;
      box-sizing: border-box;
      word-wrap: break-word;
      color: #333;
      font: 14px/1.3 '\5FAE\8F6F\96C5\9ED1', STXihei, '\534E\6587\7EC6\9ED1', Roboto, Noto, arial, sans-serif;
      background-color: #f8cc3e;
    }
    img {
      display: block;
      max-width 100%;
    }
    dt, dd {
      margin: 0;
    }
    dl {
      background-color: #fff;
      -webkit-border-radius: 3px;
      -moz-border-radius: 3px;
      border-radius: 3px;
      overflow: hidden;
      margin: 15px;
    }
    dt {
      color: #fb4b64;
      padding: 10px;
      position: relative;
    }
    dt:before {
      content: '';
      height: 1px;
      position: absolute;
      left: 0;
      right: 0;
      -webkit-transform: scaleY(0.5);
      transform: scaleY(0.5);
      bottom: 0;
      background-color: #dbdbdb;
    }
    dd {
      padding: 10px;
      overflow: hidden;
    }
    em {
      float: left;
      background-color: #fb4b64;
      width: 18px;
      height: 18px;
      -webkit-border-radius: 100%;
      -moz-border-radius: 100%;
      border-radius: 100%;
      font-style: normal;
      color: #fff;
      text-align: center;
      line-height: 18px;
      margin-right: 10px;
    }
    .con {
      overflow: hidden;
    }
    .tips {
      color: #fff;
      padding: 0 15px 15px;
      text-align: center;
    }
    a {
      display: block;
      padding: 10px;
    }
  </style>
  <include file="public/wx_share" />
</head>
<body>
	<img width="100%" height="auto" src="STATIC_F2E/m/images/topic.jpg">
  <dl>
    <dt>活动介绍</dt>
    <dd>
      <em>1</em>
      <div class="con">用户使用邸达客户端和网站购买任意商品，都可享受首单优惠；</div>
    </dd>
    <dd>
      <em>2</em>
      <div class="con">首单减免优惠仅限使用一次，仅限于在线支付的第一单；</div>
    </dd>
  </dl>
  <dl>
    <dt>活动规则</dt>
    <dd>以满500减30为例</dd>
    <dd>
      <em>1</em>
      <div class="con">购买某一商家任意商品总额超过500元，支付时即可享受优惠；</div>
    </dd>
    <dd>
      <em>2</em>
      <div class="con">购买多个商家商品总额超过500元，且其中任一商家的商品总额超过优惠金额（即30元）时，才会享受优惠；</div>
    </dd>
    <dd>
      <em>3</em>
      <div class="con">如购买同一商家多个商品，为了您的购物方便，不支持单个商品退货，只支持商品全退。</div>
    </dd>
  </dl>
  <p id="android" class="tips">最终解释权归邸达平台所有</p>
  <p id="ios" class="tips">本活动与苹果公司无关，最终解释权归邸达所有</p>
  <script>
    var ua = navigator.userAgent;
    var android = document.getElementById('android');
    var ios = document.getElementById('ios');
    if (/iPhone/gim.test(ua)) {
      android.style.display = 'none';
    } else {
      ios.style.display = 'none';
    }
  </script>
</body>
</html>