<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>APP与WAP互通测试</title>
    <style>
        body {
            margin: 0;
            -webkit-overflow-scrolling: touch;
            background-color: #f5f5f5;
            font: 14px/1.3 '\5FAE\8F6F\96C5\9ED1', STXihei, '\534E\6587\7EC6\9ED1', Roboto, Noto, arial, sans-serif;
        }
        h1 {
            font-size: 14px;
            margin: 10px;
        }
        a,
        p {
            display: block;
            margin: 0 10px 10px;
            border: 1px solid #efefef;
            padding: 10px;
            color: #333;
            background-color: #fff;
            text-decoration: none;
        }
        input {
          -webkit-appearance: none;
          font-size: inherit;
          font-family: inherit;
          color: inherit;
          border: 1px solid #efefef;
          border-radius: 0;
        }
        .pay {
          padding: 10px 0;
          background-color: #ccc;
        }
        .pay + .pay {
          margin-top: 10px;
        }
        select {
          margin: 0 10px 10px;
        }
    </style>
    <include file="public/wx_share" />
</head>
<body>
<button onclick="self.location.reload(true);">强制刷新</button>
    <h1>测试互通</h1>
    <a href="javascript:DIDAJSBridge.callHandler('HOME', { tagName: 'home' });">去首页</a>
    <a href="javascript:DIDAJSBridge.callHandler('ORDER', { tagName: 'order', status: 0 });">去我的订单页-全部订单</a>
    <a href="javascript:DIDAJSBridge.callHandler('ORDER', { tagName: 'order', status: 1 });">去我的订单页-待付款</a>
    <a href="javascript:DIDAJSBridge.callHandler('ORDER', { tagName: 'order', status: 2 });">去我的订单页-待发货</a>
    <a href="javascript:DIDAJSBridge.callHandler('ORDER', { tagName: 'order', status: 3 });">去我的订单页-待收货</a>
    <a href="javascript:DIDAJSBridge.callHandler('ORDER', { tagName: 'order', status: 4 });">去我的订单页-已完成</a>
    <a href="javascript:DIDAJSBridge.callHandler('ORDER', { tagName: 'order', status: 5 });">去我的订单页-退货</a>
    <a href="javascript:DIDAJSBridge.callHandler('CARTS', { tagName: 'carts' });">去购物车页</a>
    <a href="javascript:DIDAJSBridge.callHandler('USER_CENTER', { tagName: 'user_center' }, function(data) { alert(JSON.stringify(data)) });">去个人中心页</a>
    <a href="javascript:DIDAJSBridge.callHandler('SHOP_HOME', { tagName: 'shop_home', shopId: 35 });">去张斯亮的店铺02</a>
    <a href="javascript:DIDAJSBridge.callHandler('SHOP_LIST', { tagName: 'shop_list' });">去店铺列表页</a>
    <a href="javascript:DIDAJSBridge.callHandler('GOODS_LIST', { tagName: 'goods_list', type: 'brand', brandId: 10 });">去金六福品牌商品列表页</a>
    <a href="javascript:DIDAJSBridge.callHandler('GOODS_LIST', { tagName: 'goods_list',type: 'new' });">去新品推荐商品列表页</a>
    <a href="javascript:DIDAJSBridge.callHandler('GOODS_LIST', { tagName: 'goods_list',type: 'bargain' });">去特价商品列表页</a>
    <a href="javascript:DIDAJSBridge.callHandler('GOODS_LIST', { tagName: 'goods_list',type: 'hot' });">去热销商品列表页</a>
    <a href="javascript:DIDAJSBridge.callHandler('GOODS_LIST', { tagName: 'goods_list', type: 'category', categoryId: 1 });">去白酒分类商品列表页</a>
    <a href="javascript:DIDAJSBridge.callHandler('GOODS_CATEGORY', { tagName: 'goods_category' });">去分类筛选页</a>
    <a href="javascript:DIDAJSBridge.callHandler('BRAND_LIST', { tagName: 'brand_list' });">去品牌列表页</a>
    <a href="javascript:DIDAJSBridge.callHandler('ADD_TO_CART', { tagName: 'add_to_cart', shopId: 1, productId: 69 });">添加购物车(尼古拉斯.大表哥.西凤古酒佳宴45度500ml*6瓶)</a>
    <a href="javascript:DIDAJSBridge.callHandler('GOODS_DETAIL', { tagName: 'goods_detail', goodsId: 31, storeId:27 });">去西凤欢庆盛世酒42度500ml*6瓶</a>
    <a href="javascript:DIDAJSBridge.callHandler('ADDRESS_LIST', {tagName: 'address_list'}, function(responseData){alert(responseData)});">去收货地址列表页</a>
    <a href="javascript:DIDAJSBridge.callHandler('QR_CODE', {tagName: 'qr_code'});">打开扫码</a>
    <a href="javascript:DIDAJSBridge.callHandler('CLOSE_WEBVIEW', {tagName: 'close_webview'});">关闭webView</a>
    <a href="javascript:DIDAJSBridge.callHandler('OPEN_WEBVIEW', { tagName: 'open_webview', url: 'https://91dida.cn/wap' });">新开webView</a>
    <a href="javascript:DIDAJSBridge.callHandler('OPEN_BROWSER', { tagName: 'open_browser', url: 'https://91dida.cn/wap' });">打开手机浏览器</a>
    <a href="javascript:DIDAJSBridge.callHandler('NAV_BAR', { tagName: 'nav_bar', toggle: true });">显示底部导航</a>
    <a href="javascript:DIDAJSBridge.callHandler('NAV_BAR', { tagName: 'nav_bar', toggle: false });">隐藏底部导航</a>
    <a href="javascript:DIDAJSBridge.callHandler('HEADER_BAR', { tagName: 'header_bar', toggle: true });">显示头</a>
    <a href="javascript:DIDAJSBridge.callHandler('HEADER_BAR', { tagName: 'header_bar', toggle: false });">隐藏头</a>
    <a href="javascript:DIDAJSBridge.callHandler('BUY_NOW', { tagName: 'buy_now', goods:[{goodsId:31,goodsCount:1},{goodsId:41,goodsCount:2},{goodsId:734,goodsCount:3}]});">再次购买</a>
    <a href="javascript:self.DIDAJSBridge.callHandler('CONFIRM_ORDER',{ tagName: 'confirm_order', type: 'cart'});">确认订单</a>
    <a href="/login.html;">去登录</a>
    <div class="pay">
      <p><span>付款id1: </span><input type="tel" id="payId1" value=""></p>
      <p><span>付款id2: </span><input type="tel" id="payId2" value=""></p>
      <a href="javascript:goPay();">去付款</a>
    </div>
    <script>
      function goPay() {
        var id1 = document.getElementById('payId1').value;
        var id2 = document.getElementById('payId2').value;
        self.DIDAJSBridge.callHandler(
          'PAY',
          { tagName: 'pay', ids: [id1, id2] }
        );
      }
    </script>
</body>
</html>
