<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="renderer" content="webkit">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <link href="/favicon.ico" type="image/x-icon" rel="shortcut icon">
  <title>百度地图</title>
  <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=D332ZLjShT2rjCSH0Gv29GkDpAYbGxx5"></script>
  <style>
    html, body {
      height: 100%;
      background-color: #fff;
    }
  	body {
      margin: 0;
      -webkit-overflow-scrolling: touch;
      -webkit-box-sizing: border-box;
      -moz-box-sizing: border-box;
      box-sizing: border-box;
      word-wrap: break-word;
      color: #333;
      font: 14px/1.3 '\5FAE\8F6F\96C5\9ED1', STXihei, '\534E\6587\7EC6\9ED1', Roboto, Noto, arial, sans-serif;
    }
    #allmap {
      width: 100%;
      height: 100%;
    }
  </style>
  <include file="public/wx_share" />
</head>
<body>
	<div id="allmap"></div>
  <script>
    // 创建Map实例
    var map = new BMap.Map("allmap");

    // 设置地图点的中心点
    var point = new BMap.Point(116.404, 39.915);

    // 将地图渲染到 DOM 中，并设置地图的显示级别
    map.centerAndZoom(point, 15);

    // 需要显示的描点
    var fixedPoint = [
      {
        lng: 116.3950850022644, 
        lat: 39.91400151330005,
        content: '<p>自提网点: 沃尔玛超市</p><p>地址: 天安门内大街75号</p><p>电话: 010-22222222</p>',
      },
      {
        lng: 116.40066920650533, 
        lat: 39.9162179772915,
        content: '自提网点: 超市<br/>地址: 天安门内大街75号<br/>电话: 010-2222322',
      }
    ];

    // 描点点击后信息窗口样式
    var infoOpts = {
      // 信息窗口宽度
      width : 200,
      // 信息窗口高度
      height: 100,
      // 信息窗口标题
      // title : "默认标题" ,
      // 自动平移
      enableAutoPan : true,
      // 信息窗口的详情内容
      // message:"亲耐滴，晚上一起吃个饭吧？戳下面的链接看下地址喔~"
    }

    /**
     * 创建自定义标注
     * @param {Object} point - 标注点的经伟度及信息窗口内容.
     * @param {Number} index - 描点的索引.
     */
    function addMarker(item, index){
      // 设置标注点的百度经伟度
      var point = new BMap.Point(item.lng, item.lat)
      // 创建一个标注点
      var marker = new BMap.Marker(point);

      // 事件绑定及设置信息窗口的相关信息
      infoHandler(marker, item.content, point, infoOpts);

      // 设置第一个默认显示
      if (index === 0) {
        var infoWindow = new BMap.InfoWindow(item.content, infoOpts);
        map.openInfoWindow(infoWindow, point);
      }
      // 将创建的标注点添加到地图中
      map.addOverlay(marker);
    }

    /**
     * 设置信息窗口的事件
     * @param {Object} marker - 标注点.
     * @param {String} content - 信息窗口的详细内容.
     * @param {Object} opts - 信息窗口的样式.
     */
    function infoHandler(marker, content, point, opts) {
      marker.addEventListener('click', function(event) {
        var infoWindow = new BMap.InfoWindow(content, opts);
        map.openInfoWindow(infoWindow, point);
      });
    }

    fixedPoint.map(function(item, index) {
      addMarker(item, index);
    });
  </script>

</body>
</html>