<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
  <meta name="renderer" content="webkit">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>选择支付方式</title>
  <style>
  	html, body {
      width: 100%;
      height: 100%;
      background-color: #f0f0f0;
    }
    ::-webkit-scrollbar {
      display: none;
    }
    body {
      margin: 0;
      -webkit-overflow-scrolling: touch;
      -webkit-box-sizing: border-box;
      -moz-box-sizing: border-box;
      box-sizing: border-box;
      word-wrap: break-word;
      color: #333;
      text-align: center;
      font: 14px/1.3 "\5FAE\8F6F\96C5\9ED1", STXihei, "\534E\6587\7EC6\9ED1", Roboto, Noto, arial, sans-serif;
    }
    .pay-wrapper {
      width: 100%;
      max-width: 720px;
      text-align: left;
      display: inline-block;
      position: relative;
      -webkit-box-sizing: border-box;
      -moz-box-sizing: border-box;
      box-sizing: border-box;
      padding: 10px;
    }

    .pay-wrapper h5 {
      margin: 0;
      font-weight: 400;
    }

    .pay-wrapper .price {
      background-color: #fff;
      border-radius: 3px;
      overflow: hidden;
      padding: 10px;
      margin-bottom: 10px;
    }

    .pay-wrapper .price strong {
      float: right;
      color: #fd4d3e;
    }

    .pay-wrapper .pay-method {
      background-color: #fff;
      border-radius: 3px;
    }
    
    .pay-wrapper .pay-method .title {
      padding: 10px;
    }

    .pay-wrapper .pay-method .item {
      display: block;
      padding: 10px;
      position: relative;
    }

    .pay-wrapper .pay-method .item:before {
      content: '';
      height: 1px;
      position: absolute;
      left: 0;
      right: 0;
      -webkit-transform: scaleY(0.5);
      transform: scaleY(0.5);
      z-index: 1;
      top: 0;
      background-color: #e5e5e5;
    }

    .pay-wrapper em[class^='icon-pay-'] {
      float: left;
      width: 36px;
      height: 36px;
      margin-right: 10px;
      background: url(STATIC_F2E/m/images/icon_pay.png) 0 0 no-repeat;
      -webkit-background-size: 113px 36px;
      background-size: 113px 36px;
    }
    .pay-wrapper em.icon-pay-alipay {
      background-position: -39px 0;
    }

    .pay-wrapper em.icon-pay-wechat {
      background-position: -77px 0;
    }

    .pay-wrapper .pay-method h5 {
      font-size: 14px;
    }

    .pay-wrapper .pay-method h5, .pay-wrapper .pay-method p {
      overflow: hidden;
    }

    .pay-wrapper .pay-method p {
      color: #999;
      font-size: 12px;
      margin-top: 3px;
      margin-bottom: 0;
    }
    em.icon-more {
      position: absolute;
      top: 0;
      right: 0;
      bottom: 0;
      padding: 10px;
      background: none;
    }

    em.icon-more:before {
      content: '';
      position: absolute;
      top: 0;
      right: 10px;
      bottom: 0;
      margin: auto;
      border-left: 1px solid #e5e5e5;
      border-top: 1px solid #e5e5e5;
      width: 10px;
      height: 10px;
      -webkit-transform: rotate(135deg);
      -moz-transform: rotate(135deg);
      transform: rotate(135deg);
    }
    .loading {
      position: fixed;
      left: 0;
      top: 0;
      right: 0;
      bottom: 0;
      background-color: rgba(0, 0, 0, 0.005);
      z-index: 10;
      display: none;
    }

    .loading .text {
      position: absolute;
      left: 50%;
      margin: 0 0 0 -40px;
      top: 280px;
      color: #fff;
    }

    .loading .leaf-outer {
      position: absolute;
      left: 50%;
      top: 200px;
      width: 120px;
      height: 120px;
      margin-left: -60px;
      background: rgba(40, 40, 40, 0.75);
      border-radius: 5px;
    }

    .loading .leaf-inner {
      position: absolute;
      width: 0;
      z-index: 1;
      left: 50%;
      top: 38%;
    }

    .loading .leaf {
      position: absolute;
      top: -1px;
      opacity: .25;
    }

    .loading .leaf:before {
      content: " ";
      position: absolute;
      width: 8.14px;
      height: 3.08px;
      background: #d1d1d5;
      box-shadow: 0 0 1px rgba(0, 0, 0, 0.0980392);
      border-radius: 1px;
      -webkit-transform-origin: left 50% 0;
      transform-origin: left 50% 0;
    }

    .loading .leaf-0 {
      -webkit-animation: f 1.25s linear infinite;
      animation: f 1.25s linear infinite;
    }

    .loading .leaf-0:before {
      -webkit-transform: rotate(0deg) translate(7.92px);
      transform: rotate(0deg) translate(7.92px);
    }

    .loading .leaf-1 {
      -webkit-animation: g 1.25s linear infinite;
      animation: g 1.25s linear infinite;
    }

    .loading .leaf-1:before {
      -webkit-transform: rotate(30deg) translate(7.92px);
      transform: rotate(30deg) translate(7.92px);
    }

    .loading .leaf-2 {
      -webkit-animation: h 1.25s linear infinite;
      animation: h 1.25s linear infinite;
    }

    .loading .leaf-2:before {
      -webkit-transform: rotate(60deg) translate(7.92px);
      transform: rotate(60deg) translate(7.92px);
    }

    .loading .leaf-3 {
      -webkit-animation: i 1.25s linear infinite;
      animation: i 1.25s linear infinite;
    }

    .loading .leaf-3:before {
      -webkit-transform: rotate(90deg) translate(7.92px);
      transform: rotate(90deg) translate(7.92px);
    }

    .loading .leaf-4 {
      -webkit-animation: j 1.25s linear infinite;
      animation: j 1.25s linear infinite;
    }

    .loading .leaf-4:before {
      -webkit-transform: rotate(120deg) translate(7.92px);
      transform: rotate(120deg) translate(7.92px);
    }

    .loading .leaf-5 {
      -webkit-animation: k 1.25s linear infinite;
      animation: k 1.25s linear infinite;
    }

    .loading .leaf-5:before {
      -webkit-transform: rotate(150deg) translate(7.92px);
      transform: rotate(150deg) translate(7.92px);
    }

    .loading .leaf-6 {
      -webkit-animation: l 1.25s linear infinite;
      animation: l 1.25s linear infinite;
    }

    .loading .leaf-6:before {
      -webkit-transform: rotate(180deg) translate(7.92px);
      transform: rotate(180deg) translate(7.92px);
    }

    .loading .leaf-7 {
      -webkit-animation: m 1.25s linear infinite;
      animation: m 1.25s linear infinite;
    }

    .loading .leaf-7:before {
      -webkit-transform: rotate(210deg) translate(7.92px);
      transform: rotate(210deg) translate(7.92px);
    }

    .loading .leaf-8 {
      -webkit-animation: n 1.25s linear infinite;
      animation: n 1.25s linear infinite;
    }

    .loading .leaf-8:before {
      -webkit-transform: rotate(240deg) translate(7.92px);
      transform: rotate(240deg) translate(7.92px);
    }

    .loading .leaf-9 {
      -webkit-animation: o 1.25s linear infinite;
      animation: o 1.25s linear infinite;
    }

    .loading .leaf-9:before {
      -webkit-transform: rotate(270deg) translate(7.92px);
      transform: rotate(270deg) translate(7.92px);
    }

    .loading .leaf-10 {
      -webkit-animation: p 1.25s linear infinite;
      animation: p 1.25s linear infinite;
    }

    .loading .leaf-10:before {
      -webkit-transform: rotate(300deg) translate(7.92px);
      transform: rotate(300deg) translate(7.92px);
    }

    .loading .leaf-11 {
      -webkit-animation: q 1.25s linear infinite;
      animation: q 1.25s linear infinite;
    }

    .loading .leaf-11:before {
      -webkit-transform: rotate(330deg) translate(7.92px);
      transform: rotate(330deg) translate(7.92px);
    }

    @-webkit-keyframes f {
      0% {
        opacity: .25;
      }

      0.01% {
        opacity: .25;
      }

      0.02% {
        opacity: 1;
      }

      60.01% {
        opacity: .25;
      }

      to {
        opacity: .25;
      }
    }

    @-webkit-keyframes g {
      0% {
        opacity: .25;
      }

      8.34333% {
        opacity: .25;
      }

      8.35333% {
        opacity: 1;
      }

      68.3433% {
        opacity: .25;
      }

      to {
        opacity: .25;
      }
    }

    @-webkit-keyframes h {
      0% {
        opacity: .25;
      }

      16.6767% {
        opacity: .25;
      }

      16.6867% {
        opacity: 1;
      }

      76.6767% {
        opacity: .25;
      }

      to {
        opacity: .25;
      }
    }

    @-webkit-keyframes i {
      0% {
        opacity: .25;
      }

      25.01% {
        opacity: .25;
      }

      25.02% {
        opacity: 1;
      }

      85.01% {
        opacity: .25;
      }

      to {
        opacity: .25;
      }
    }

    @-webkit-keyframes j {
      0% {
        opacity: .25;
      }

      33.3433% {
        opacity: .25;
      }

      33.3533% {
        opacity: 1;
      }

      93.3433% {
        opacity: .25;
      }

      to {
        opacity: .25;
      }
    }

    @-webkit-keyframes k {
      0% {
        opacity: .27095833;
      }

      41.6767% {
        opacity: .25;
      }

      41.6867% {
        opacity: 1;
      }

      1.67667% {
        opacity: .25;
      }

      to {
        opacity: .27095833;
      }
    }

    @-webkit-keyframes l {
      0% {
        opacity: .375125;
      }

      50.01% {
        opacity: .25;
      }

      50.02% {
        opacity: 1;
      }

      10.01% {
        opacity: .25;
      }

      to {
        opacity: .375125;
      }
    }

    @-webkit-keyframes m {
      0% {
        opacity: .47929167;
      }

      58.3433% {
        opacity: .25;
      }

      58.3533% {
        opacity: 1;
      }

      18.3433% {
        opacity: .25;
      }

      to {
        opacity: .47929167;
      }
    }

    @-webkit-keyframes n {
      0% {
        opacity: .58345833;
      }

      66.6767% {
        opacity: .25;
      }

      66.6867% {
        opacity: 1;
      }

      26.6767% {
        opacity: .25;
      }

      to {
        opacity: .58345833;
      }
    }

    @-webkit-keyframes o {
      0% {
        opacity: .687625;
      }

      75.01% {
        opacity: .25;
      }

      75.02% {
        opacity: 1;
      }

      35.01% {
        opacity: .25;
      }

      to {
        opacity: .687625;
      }
    }

    @-webkit-keyframes p {
      0% {
        opacity: .79179167;
      }

      83.3433% {
        opacity: .25;
      }

      83.3533% {
        opacity: 1;
      }

      43.3433% {
        opacity: .25;
      }

      to {
        opacity: .79179167;
      }
    }

    @-webkit-keyframes q {
      0% {
        opacity: .89595833;
      }

      91.6767% {
        opacity: .25;
      }

      91.6867% {
        opacity: 1;
      }

      51.6767% {
        opacity: .25;
      }

      to {
        opacity: .89595833;
      }
    }

  </style>
  <include file="public/wx_share" />
</head>
<body>
  <div class="loading" id='loading'>
    <div class="leaf-outer">
      <div class="leaf-inner">
        <em class="leaf leaf-0"></em>
        <em class="leaf leaf-1"></em>
        <em class="leaf leaf-2"></em>
        <em class="leaf leaf-3"></em>
        <em class="leaf leaf-4"></em>
        <em class="leaf leaf-5"></em>
        <em class="leaf leaf-6"></em>
        <em class="leaf leaf-7"></em>
        <em class="leaf leaf-8"></em>
        <em class="leaf leaf-9"></em>
        <em class="leaf leaf-10"></em>
        <em class="leaf leaf-11"></em>
      </div>
    </div>
    <p class="text">努力加载中...</p>
  </div>
  <div class="wrapper pay-wrapper">
    <div class="price">
      <span>订单金额:</span>
      <strong>¥{$payment['grand_total']}</strong>
    </div>
    <div class="pay-method">
      <h5 class="title">在线支付方式</h5>
      <volist name='payment.payment_list' id='item'>
        <eq name='item.id' value='4'>
          <a onclick='goPayment("{$item.payment_code}")' class="item" data-id='{$item.id}'>
            <em class="icon-pay-yb"></em>
            <h5>易宝支付</h5>
            <p>支持易宝支付</p>
            <em class="icon-more"></em>
          </a>
        </eq>
        <eq name='item.id' value='1'>
          <a onclick='goPayment("{$item.payment_code}")' class="item" data-id='{$item.id}'>
            <em class="icon-pay-alipay"></em>
            <h5>支付宝</h5>
            <p>推荐使用支付宝账号的用户</p>
            <em class="icon-more"></em>
          </a>
        </eq>
        <eq name='item.id' value='2'>
          <a onclick='goPayment("{$item.payment_code}")' class="item" data-id='{$item.id}'>
            <em class="icon-pay-wechat"></em>
            <h5>微信支付</h5>
            <p>建议微信5.0版本以上的用户使用</p>
            <em class="icon-more"></em>
          </a>
        </eq>
      </volist>
    </div>
  </div>
  <script>
    function $fetch(body, url, callback) {
      var xhr = new XMLHttpRequest();
      xhr.open("POST", url, true);
      xhr.onreadystatechange = function () {
        if (xhr.readyState == 4 && xhr.status == 200) {
          var data = self.JSON.parse(xhr.responseText);
          if (data.result === 'success') {
            callback(data);
          } else {
            self.toast(data.info.errmsg);
          }
          xhr = null;
        }
      };
      xhr.setRequestHeader("Content-Type","application/x-www-form-urlencoded"); 
      xhr.send(body);
    }

    function goPayment(code) {
      var order_ids = {$payment['order_ids']};
      loading();
      if (code === 'yeepay') {
        var body = {
          order_ids: order_ids,
          api: 'payment',
          method: 'get_yeepay_no',
        }
        $fetch(serialize(body), '/index/fetch', function(data) {
          self.location.href = data.info.payurl;
          loading(true);
        });
      } else if (code === 'alipay') {
        var body = {
          order_ids: order_ids,
        }
        $fetch(serialize(body), '/pay/alipay', function(data) {
          self.location.href = data.info.payurl;
          loading(true);
        });
      } else {
        self.location.href = '/pay/wxpay';
      }
    }

    var $el = null;
    var mask = null;
    if (!$el) {
      $el = self.document.createElement('div');
      $el.style.position = 'fixed';
      $el.style.left = '50%';
      $el.style.top = '50%';
      $el.style.zIndex = 5;
      $el.style.padding = '10px';
      $el.style.color = '#fff';
      $el.style.borderRadius = '5px';
      $el.style.backgroundColor = 'rgba(40, 40, 40, .75)';
      $el.style.webkitTransform = 'translate(-50%, -50%)';
      $el.style.transform = 'translate(-50%, -50%)';
      $el.style.display = 'none';
      self.document.body.appendChild($el);
    }
    if (!mask) {
      mask = self.document.createElement('div');
      mask.style.position = 'fixed';
      mask.style.left = 0;
      mask.style.top = 0;
      mask.style.right = 0;
      mask.style.bottom = 0;
      mask.style.zIndex = 4;
      mask.style.backgroundColor = 'rgba(0, 0, 0, .01)';
      mask.style.display = 'none';
      self.document.body.appendChild(mask);
    }
    function toast(content) {
      $el.innerHTML = content;
      $el.style.display = 'block';
      mask.style.display = 'block';
      self.setTimeout(function() {
        $el.style.display = 'none';
        mask.style.display = 'none';
      }, 2000);
    };

    function serialize(sourceParams) {
      if (typeof sourceParams === 'string') return sourceParams;
      var params = [];
      var add = function add(key, value) {
        params[params.length] = encodeURIComponent(key) + '=' + encodeURIComponent(value);
      };

      for (var i in sourceParams) {
        if (typeof sourceParams[i] === 'object') {
          if (Array.isArray(sourceParams[i])) {
            var key = i + '[]';
            sourceParams[i].map(function(item) {
              add(key, item);
            });
          } else {
            var keys =  self.Object.keys(sourceParams[i]);
            keys.map(function(item) {
              add(i + item, sourceParams[i][item]);
            });
          }
        } else {
          add(i, sourceParams[i]);
        }
      }
      return params.join('&').replace('/%20/g', '+');
    };

    function loading(toggle) {
      var loadEl = document.getElementById('loading');
      if (toggle) {
        self.document.body.style.overflow = 'auto';
        loadEl.style.display = 'none';
      } else {
        self.document.body.style.overflow = 'hidden';
        loadEl.style.display = 'block';
      }
    }

  </script>
</body>
</html>