<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
  <meta name="renderer" content="webkit">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>支付帮助</title>
  <style>
  *{
    margin:0;
    padding: 0;
  }
  	html, body {
      background-color: #fff;
    }
    body {
      margin: 0;
      -webkit-overflow-scrolling: touch;
      -webkit-box-sizing: border-box;
      -moz-box-sizing: border-box;
      box-sizing: border-box;
      word-wrap: break-word;
      color: #333;
      padding: 15px;
      font: 14px/1.3 '\5FAE\8F6F\96C5\9ED1', STXihei, '\534E\6587\7EC6\9ED1', Roboto, Noto, arial, sans-serif;
    }

    a{
        text-decoration: none;
    }
    .header{
        text-align: center;
    }
    .header h3{
      font-size: 14px;
    }
    .body{
        margin-bottom: 20px;
    }

    .body dl{
        margin-top:10px;
    }
    .body p{
        line-height:20px;
    }
  </style>
  <include file="public/wx_share" />
</head>
<body>
<div class="header">
    <h3>在线支付问题知识列表</h3>
</div>
<div class="body">
    <dl>
        <dt><h4>1.如何使用优惠券支付？</h4></dt>
        <dd>
            <p>（1）选购商品加入购物车 并下单然后请选择支付方式：支付平台；</p>
            <p>（2）选择可用优惠券或者添加已知优惠券编码；</p>
            <p>（3）确认订单去支付；</p>
            <p>（4）选择支付方式——货到付款、易宝支付、支付宝支付、微信支付；</p>
            <p>（5）确认并完成支付。</p>
            <p><strong>友情提示：优惠券在满足其使用条件下方能使用。</strong></p>
        </dd>
    </dl>
    <dl>
        <dt><h4>2.如何使用公司转账？</h4></dt>
        <dd>
            <p>（1）在支付页面，选择易宝支付；</p>
            <p>（2）选择对应的银行对公版；</p>
            <p>（3）进入企业网银支付。</p>
            <p><strong>企业对公账户更优惠和快捷哦。</strong></p>
        </dd>
    </dl>
    <dl>
        <dt><h4>3.付款后没有收到商品怎么办？</h4></dt>
        <dd>
            <p>如在线支付款项但是没有收到货，请直接联系在线客服或者是商家客服处理您的问题即可，谢谢。</p>
        </dd>
    </dl>
    <dl>
        <dt><h4>4.是否支持刷卡、现金混合支付？</h4></dt>
        <dd>
            <p>您好，目前暂时不支持刷卡现金混合支付，祝您购物愉快，谢谢。</p>
        </dd>
    </dl>
    <dl>
        <dt><h4>5.在线支付常见问题</h4></dt>
        <dd>
            <p>（1）在收银台可以用其他支付方式吗？</p>
            <p>在线支付，指除了货到付款之外的一切支付方式，目前邸达平台支持易宝支付、支付宝支付、微信支付等方式。</p>
            <p>（2）用户手机丢了，如何保证在线支付绑卡的安全？</p>
            <p>用户手机丢了，可以通过以下途径来保护自己的绑卡安全：</p>
            <p>λ 致电手机号预留的所属银行客服，冻结或注销银行卡；</p>
            <p>λ 致电网银在线的客服电话：<a href="tel:4006226586">400 6226 586</a>，提供给客服人员用户的手机号、卡号等信息，然后申请解绑银行卡。</p>
        </dd>
    </dl>
    <dl>
        <dt><h4>6. 为什么要进行身份验证？</h4></dt>
        <dd>
            <p>（1）为保障您的账户信息安全，在变更账户中的重要信息时需要进行身份验证，感谢您的理解和支持。</p>
            <p>（2）验证身份遇到问题？请说明用户名，手机号，拨打<a href="tel:4000798798">4000-798-798</a>咨询。</p>
        </dd>
    </dl>
</div>
</body>
</html>
