<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
  <meta name="renderer" content="webkit">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>用户协议</title>
  <style>
  	html, body {
      background-color: #fff;
    }
    body {
      margin: 0;
      -webkit-overflow-scrolling: touch;
      -webkit-box-sizing: border-box;
      -moz-box-sizing: border-box;
      box-sizing: border-box;
      word-wrap: break-word;
      color: #333;
      padding: 15px 3%;
      font: 14px/1.3 '\5FAE\8F6F\96C5\9ED1', STXihei, '\534E\6587\7EC6\9ED1', Roboto, Noto, arial, sans-serif;
    }
    h2 {
      margin: 10px;
      text-align: center;
    }
    h3 {
      margin-bottom: 10px;
      margin-top: 20px;
    }
    p {
      margin-bottom: 10px;
      text-indent: 2em;
    }
  </style>
  <include file="public/wx_share" />
</head>
<body>
{$info}
</body>
</html>