<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
  <meta name="renderer" content="webkit">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>店铺详情</title>
  <style>
  	html, body {
      width: 100%;
      height: 100%;
      background-color: #f0f0f0;
    }
    ::-webkit-scrollbar {
      display: none;
    }
    body {
      margin: 0;
      -webkit-overflow-scrolling: touch;
      -webkit-box-sizing: border-box;
      -moz-box-sizing: border-box;
      box-sizing: border-box;
      word-wrap: break-word;
      color: #333;
      text-align: center;
      font: 14px/1.3 "\5FAE\8F6F\96C5\9ED1", STXihei, "\534E\6587\7EC6\9ED1", Roboto, Noto, arial, sans-serif;
    }

    .shop-wrapper-topic {
      position: relative;
      padding-top: 33%;
      background-repeat: no-repeat;
      background-position: 50% 50%;
      background-size: cover;
    }

    .shop-wrapper-topic:before {
      position: absolute;
      content: '';
      left: 0;
      top: 0;
      right: 0;
      bottom: 0;
      background-color: rgba(0, 0, 0, 0.3);
    }

    .shop-wrapper-topic .logo {
      z-index: 1;
      position: absolute;
      bottom: 12%;
      left: 5%;
      width: 15%;
      height: 30%;
      border: 2px solid #fff;
      background-repeat: no-repeat;
      background-position: 50% 50%;
      background-size: cover;
    }

    .shop-wrapper-topic .name,
    .shop-wrapper-topic .tips {
      z-index: 1;
      position: absolute;
      left: 25%;
      color: #fff;
      font-size: 16px;
      text-shadow: 1px 1px 0 #333;
    }
    .shop-wrapper-topic .name {
      bottom: 28%;
    }
    .shop-wrapper-topic .tips {
      bottom: 13%;
      font-size: 12px;
    }

    .shop-wrapper-topic .collection {
      position: absolute;
      right: 0;
      bottom: 12%;
      color: #fff;
      padding: 5px 10px;
      border-top-left-radius: 3px;
      border-bottom-left-radius: 3px;
      background-color: #fd4d3e;
    }
    .icon-shop-collection {
      display: inline-block;
      width: 13px;
      height: 12px;
      margin-right: 3px;
      background-position: 50% 50%;
      background-repeat: no-repeat;
      -webkit-background-size: contain;
      background-size: contain;
      background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAYCAYAAADkgu3FAAAB4UlEQVRIibXWMWsUURSG4Uk2xJjCIBoQYxcwFppOCzFEG8VGBMFey6DgHxD/gpjCQrEQBCUGQlCRwIJBjZZKCiFGsRB0QUkUQcXIY7Fn3evq7s7G3QsDM+d853vP3Lkzd7IsGejBKRSxojxKuIkDWc3A/siVQruCeZxGT62+UjSMZ6qjhEV8TmJX0BvH5ST+JbTvk9hzjNRCtuNtCKYxmuQKOIalJD8V5y9xHIVEvxu3k2aHUtBcJC7883bLmk14nHT8BAMN9OdD96ASGI/AbL2ipHgbVvHpj07r62fC+0iGa3Ex2qwwis/iXE7tnvC+nuEV3uQpXM/47Y+vmOsg6D6+Z/iG+Q6CiljL8CLWf3cHIF14h6UMl+KBHewAaCy8JzPsjYtiB0CV93NfJXA3AifbCDkRnvfS4HAsio/Y0QbIED6E587a5ER0sICN/wHZgEfhdaae6FYIpiUfyhYg3aof3Cl01RP2Jd3caAUWS7mydSygv1nBFuW9JTdMeSu5GjWL2Jq3u8EENoO+BtremOoKZDAXJDEYiCkQ0/lXl3H3D0PzFJtbgiRG/ZgNo9fYleRGsBy5O02fSQ5YARfDcBVHcVj152VyPSu0EXACP/AzjrW670kbYOPKPynLONRK7S/dRxQhMF4F1QAAAABJRU5ErkJggg==);
    }

    .shop-wrapper-topic .active .icon-shop-collection {
      background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAYCAYAAADkgu3FAAACUUlEQVRIibWWzUuUURTGjx+YuUjChBhFhvHl3vs8VLtaRGFtijYRBO1rGQX9A9G/ELloUbQQAsMCkYoQhCSzloWLwCxaBCkUWgQZGU+LuXN7lRkddbzwLt57nnN+59xvs1yTWau8vyhyQuSiSIlcEDAs547ZmqYQjgoYFrkQtYsCJkVeklnrWn3ZKcv6Rb6JDhXAjIAfqQ+4I7M2mbUJuJ3T/hQwI3I+p30r7/1qiPcFAZ+j4JG8P5SrskXenxUwm+zkSAz4XsA5mbUkPXBA5MOUrHM9ljOOi5RCuFG13HLFewS8zGX8SqVSZ009cD3qnlfGeSA6j9VySs7F4n4BSwK+r8q0Nmw0FnDaRN4TqfxwrescwlUB1+rUHoxVDZnIDwI+1eO4lZbiC/glYHwHQc9E/jYBywImdxA0IWDFRL4TOS+z5oZDzJpEfhEwayJvxZVxouEg8nhc0YMm5w7Hn4mGgyr707kjlY4nEXahYZAQzsel/fR/Z5b1C1gW+U1Z1rttiHM9Ar4KWFYIbrURuBwzmFZv7+4tQ7Jsl8ipOO9XqouAB+ngzB2UdUPMmnMH7ojMmqoLi8X2lA15fzMwmTWlqwOYVqHQsb5DCF3xbqkbJrMWAXcjZEbO7asvuyzrTjBgVMVi+zqQtnhHlSFZ1l0XJAUolToFTMfKpqplqRC6RL6IkNfq69u7KUgKVCh0iByLgT7KuZBs3nuRc9H2eMM52RBWHv+bMeCSyDMK4VTu8TK4lRVaG1jeZ38E/I3fSs19sm1YCAPxkTIn709uxvcfBXafN36UbMIAAAAASUVORK5CYII=);
    }

    .shop-wrapper-topic .active {
      background-color: #fff;
      color: #fd4d3e;
    }

    .shop-wrapper-topic .collection em, .shop-wrapper-topic .collection span {
      vertical-align: middle;
      pointer-events: none;
    }

    .shop-info-wrapper {
      width: 100%;
      max-width: 720px;
      text-align: left;
      display: inline-block;
      position: relative;
      -webkit-box-sizing: border-box;
      -moz-box-sizing: border-box;
      box-sizing: border-box;
      min-height: 100%;
      background-color: #fff;
    }

    .shop-info-wrapper .shop-info {
      padding: 10px;
    }

    .shop-info-wrapper .shop-info dt {
      margin-bottom: 5px;
    }

    .shop-info-wrapper .shop-info dd {
      color: #999;
      margin-bottom: 10px;
      margin-left: 0;
    }

    .shop-info-wrapper .shop-info img {
      width: 100%;
      border: 1px solid #ccc;
      padding: 5px;
      box-sizing: border-box;
      border-radius: 5px;
    }
  </style>
  <include file="public/wx_share" />
</head>
<body>
  <div class="wrapper shop-info-wrapper">
    <header class="shop-wrapper-topic" style="background-image: url({$info['store']['banner']})">
      <a class="logo" style="background-image: url({$info['store']['logo']})"></a>
      <span class="name">{$info['store']['store_name']}</span>
      <span class="tips">{$info['store']['starting_price_tips']}</span>
      <if condition="$info['store']['is_collection'] eq 1">
        <a id='collection' class="collection active">
          <em class="icon-shop-collection"></em>
          <span>已收藏</span>
        </a>
      <else />
        <a id='collection' class="collection">
          <em class="icon-shop-collection"></em>
          <span>收藏</span>
        </a>
      </if>
    </header>
    <dl class="shop-info">
      <dt>公司名称:</dt>
      <dd>{$info['company']['company_name']}</dd>
      <dt>店铺简介:</dt>
      <dd>{$info['company']['company_intro']}</dd>
      <dt>营业执照:</dt>
      <dd>
        <img src="{$info['company']['business_license']}" alt="">
      </dd>
      <dt>经营资质:</dt>
      <volist name="info['company']['business_qualification']" id='item'>
        <dd>
          <img src="{$item}" alt="">
        </dd>
      </volist>
    </dl>
  </div>
  <script>
    var collection = self.document.getElementById('collection');
    collection.addEventListener('click', function(event) {
      var _t = event.target;
      var _span = _t.getElementsByTagName('span')[0];
      var cls = _t.className;
      var type = 0;
      if (cls.indexOf('active') !== -1) {
        type = 0
      } else {
        type = 1;
      }
      

      var xhr = new XMLHttpRequest();
      var body = 'api=favorites&store_id={$info["store"]["entity_id"]}&method=' + (type? 'add_store_wish': 'remove_store_wish');
      xhr.open("POST", '/index/fetch', true);
      xhr.onreadystatechange = function () {
        if (xhr.readyState == 4 && xhr.status == 200) {
          var data = self.JSON.parse(xhr.responseText);
          if (data.result === 'success') {
            if (type) {
              _t.className = 'collection active';
              _span.innerHTML = '已收藏';
            } else {
              _t.className = 'collection';
              _span.innerHTML = '收藏';
            }
            self.toast('操作成功');
          } else {
            self.toast(data.info.errmsg);
          }
          xhr = null;
        }
      };
      xhr.setRequestHeader("Content-Type","application/x-www-form-urlencoded"); 
      xhr.send(body);
    });

    var $el = null;
    var mask = null;
    if (!$el) {
      $el = self.document.createElement('div');
      $el.style.position = 'fixed';
      $el.style.left = '50%';
      $el.style.top = '50%';
      $el.style.zIndex = 5;
      $el.style.padding = '10px';
      $el.style.color = '#fff';
      $el.style.borderRadius = '5px';
      $el.style.backgroundColor = 'rgba(40, 40, 40, .75)';
      $el.style.webkitTransform = 'translate(-50%, -50%)';
      $el.style.transform = 'translate(-50%, -50%)';
      $el.style.display = 'none';
      self.document.body.appendChild($el);
    }
    if (!mask) {
      mask = self.document.createElement('div');
      mask.style.position = 'fixed';
      mask.style.left = 0;
      mask.style.top = 0;
      mask.style.right = 0;
      mask.style.bottom = 0;
      mask.style.zIndex = 4;
      mask.style.backgroundColor = 'rgba(0, 0, 0, .01)';
      mask.style.display = 'none';
      self.document.body.appendChild(mask);
    }
    function toast(content) {
      $el.innerHTML = content;
      $el.style.display = 'block';
      mask.style.display = 'block';
      self.setTimeout(function() {
        $el.style.display = 'none';
        mask.style.display = 'none';
      }, 2000);
    };
  </script>
</body>
</html>