<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="renderer" content="webkit">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>微信支付</title>
  <style>
    body {
      text-align: center;
      padding: 50px 15px 0;
      color: #333;
      text-align: center;
      font: 14px/1.3 'Microsoft YaHei', '\5FAE\8F6F\96C5\9ED1', STXihei, '\534E\6587\7EC6\9ED1', Roboto, Noto, arial, sans-serif;
    }
    h4 {
      font-size: 18px;
      font-weight: 400;
    }
    p {
      font-size: 32px;
      margin-bottom: 50px;
      font-weight: 700;
    }
    .btn {
      height: 45px;
      line-height: 45px;
      text-decoration: none;
      color: #fff;
      display: block;
      width: 96%;
      margin: 20px auto 10px;
      border-radius: 5px;
      text-align: center;
      background-color: #52b75a;
    }
  </style>
  <script type="text/javascript">
    function jsApiCall(){
      WeixinJSBridge.invoke(
        'getBrandWCPayRequest',
        <?php echo $jsApiParameters; ?>,
        function(res){
          if (res.err_msg == 'get_brand_wcpay_request:ok') {
            self.location.href = '/#/pay/success';
          } else if (res.err_msg == 'get_brand_wcpay_request:fail')  {
            self.location.href = '/#/pay/fail';
          }
        }
      );
    }

    function callpay(){
      if (typeof WeixinJSBridge == "undefined"){
        if( document.addEventListener ){
          document.addEventListener('WeixinJSBridgeReady', jsApiCall, false);
        }else if (document.attachEvent){
          document.attachEvent('WeixinJSBridgeReady', jsApiCall);
          document.attachEvent('onWeixinJSBridgeReady', jsApiCall);
        }
      }else{
        jsApiCall();
      }
    }
  </script>
</head>
<body>
  <h4>本次支付金额</h4>
  <p>¥{$info['grand_total']}元</p>
  <a class='btn' onclick='callpay()'>立即支付</a>
</body>
</html>
